"""Static configuration and mappings"""

# Exchange emojis for notifications
EXCHANGE_EMOJIS = {
    'coinbase': '🟦',
    'kraken': '🐙',
    'mexc': '🟪',
    'binance': '🟨',
    'bybit': '🟩',
    'okx': '🟥'
}

# Stablecoins to skip
STABLECOINS = {
    'USDT', 'USDC', 'DAI', 'BUSD', 'TUSD', 'USDP', 
    'GUSD', 'LUSD', 'FRAX', 'PAX', 'FDUSD', 'PYUSD',
    'USDJ', 'USDD', 'USDK', 'EURS', 'CEUR', 'EUROC',
    'EURT', 'EURI'
}

# Comprehensive coin mapping (for fallback only)
COIN_MAPPING = {
    'BTC': 'bitcoin',
    'ETH': 'ethereum',
    'USDT': 'tether',
    'BNB': 'binancecoin',
    'SOL': 'solana',
    'XRP': 'ripple',
    'USDC': 'usd-coin',
    'ADA': 'cardano',
    'AVAX': 'avalanche-2',
    'DOGE': 'dogecoin',
    'TRX': 'tron',
    'DOT': 'polkadot',
    'LINK': 'chainlink',
    'WBTC': 'wrapped-bitcoin',
    'ICP': 'internet-computer',
    'SHIB': 'shiba-inu',
    'DAI': 'dai',
    'LTC': 'litecoin',
    'BCH': 'bitcoin-cash',
    'UNI': 'uniswap',
    'ATOM': 'cosmos',
    'ETC': 'ethereum-classic',
    'XLM': 'stellar',
    'TON': 'the-open-network',
    'FIL': 'filecoin',
    'APT': 'aptos',
    'ARB': 'arbitrum',
    'HBAR': 'hedera-hashgraph',
    'VET': 'vechain',
    'QNT': 'quant-network',
    'MKR': 'maker',
    'RUNE': 'thorchain',
    'ALGO': 'algorand',
    'EGLD': 'elrond-erd-2',
    'FLOW': 'flow',
    'AAVE': 'aave',
    'AXS': 'axie-infinity',
    'SAND': 'the-sandbox',
    'MANA': 'decentraland',
    'XTZ': 'tezos',
    'THETA': 'theta-token',
    'FTM': 'fantom',
    'NEO': 'neo',
    'KAVA': 'kava',
    'ROSE': 'oasis-network',
    'GALA': 'gala',
    'ENJ': 'enjincoin',
    'KAS': 'kaspa',
    'PEPE': 'pepe',
    'BONK': 'bonk',
    'WIF': 'dogwifcoin',
    'FLOKI': 'floki',
    'SUI': 'sui',
    'SEI': 'sei-network',
    'TIA': 'celestia',
    'DYM': 'dymension',
    'STRK': 'starknet',
    'W': 'wormhole',
    'JUP': 'jupiter',
    'PYTH': 'pyth-network',
    'ONDO': 'ondo-finance',
    'ENA': 'ethena',
    'ETHFI': 'ether-fi',
    'ALT': 'altlayer',
    'PORTAL': 'portal',
    'AXL': 'axelar',
    'MANTA': 'manta-network',
    'PIXEL': 'pixel',
    'AEVO': 'aevo',
    'OMNI': 'omni-network',
    'REZ': 'rez',
    'SAGA': 'saga-2',
    'TAO': 'bittensor',
    'FET': 'fetch-ai',
    'RNDR': 'render-token',
    'PENDLE': 'pendle',
    'JTO': 'jito-governance-token',
    'WLD': 'worldcoin-wld',
    'STX': 'blockstack',
    'MNT': 'mantle',
    'RETH': 'rocket-pool-eth',
    'RDNT': 'radiant-capital',
    'CYBER': 'cyberconnect',
    'ARKM': 'arkham',
    'BLUR': 'blur',
    'MEME': 'meme',
    'ORDI': 'ordinals',
    'SATS': 'sats-hundred',
    'NOT': 'notcoin',
    'DOGS': 'dogs',
    'CATI': 'catizen',
    'HMSTR': 'hamster-kombat',
    'PIPPIN': 'pippin',
    'GOAT': 'goatseus-maximus',
    'FARTCOIN': 'fartcoin',
    'SPX': 'spx6900',
    'POPCAT': 'popcat',
    'MOG': 'mog-coin',
    'BRETT': 'brett',
    'TURBO': 'turbo',
    'COQ': 'coq-inu',
    'ANDY': 'andy',
    'BOB': 'bob-token'
}